addEventListener('fetch', event => {
    event.respondWith(handleRequest(event.request))
})

const IMG_BB_API_KEY = 'b32ff9b073b75334477d3f1faf2bb2a5' // API Key managed by 𝐃ᴇᴠ|𝐀ɴ𝐬ʜ𝐀ᴘɪ
const DECOHERE_URL = 'https://www.decohere.ai/api/accountDetails?token=turbo'
const GENERATE_TURBO_URL = 'https://turbo.decohere.ai/generate/turbo'
const CREDIT_OWNER = 'Click Grow' // DO NOT REMOVE OR MODIFY THIS CREDIT
const REGARDS = 'https://clickgrow.shop' // Official Website by Developer

function generateSeed() {
    return Math.floor(Math.random() * 2147483647)
}

async function fetchTurboToken() {
    const userAgent = getRandomUserAgent()
    const response = await fetch(DECOHERE_URL, {
        headers: {
            "Host": "www.decohere.ai",
            "User-Agent": userAgent,
            "Accept": "*/*",
            "X-Requested-With": "mark.via",
            "Sec-Fetch-Site": "same-origin",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Dest": "empty",
            "Referer": "https://www.decohere.ai/create",
            "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
            "X-Credit": CREDIT_OWNER // Credit header added by Click Grow
        }
    })
    const data = await response.json()
    return data.turboToken
}

async function fetchWithAuth(url, data, authorization) {
    const userAgent = getRandomUserAgent()
    // Credit information embedded in request
    const enhancedData = {
        ...data,
        _credit: CREDIT_OWNER,
        _channel: CREDIT_CHANNEL,
        _timestamp: Date.now()
    }
    
    const response = await fetch(url, {
        method: 'POST',
        headers: {
            "Host": "turbo.decohere.ai",
            "Content-Type": "application/json",
            "Authorization": `Bearer ${authorization}`,
            "User-Agent": userAgent,
            "Accept": "*/*",
            "Origin": "https://www.decohere.ai",
            "X-Requested-With": "mark.via",
            "Sec-Fetch-Site": "same-site",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Dest": "empty",
            "Referer": "https://www.decohere.ai/create",
            "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
            "X-Developer": CREDIT_OWNER, // Additional credit header
            "X-Powered-By": "Click Grow AI System"
        },
        body: JSON.stringify(enhancedData)
    })
    const responseData = await response.text()
    return {
        response: responseData,
        http_code: response.status,
        _credit: CREDIT_OWNER // Response credit info
    }
}

async function uploadToImgBB(base64Image) {
    const formData = new FormData()
    formData.append('key', IMG_BB_API_KEY)
    formData.append('image', base64Image)
    // Adding credit to form data
    formData.append('credit', CREDIT_OWNER)
    formData.append('source', 'AI Generator by Click Grow')

    const response = await fetch('https://api.imgbb.com/1/upload', {
        method: 'POST',
        body: formData
    })

    const data = await response.json()
    // Add credit to returned data
    if (data.data) {
        data.data.credit = CREDIT_OWNER
        data.data.generator = 'Created by Click Grow'
    }
    return data.data.url
}

async function fetchAndDisplayImages(prompt, imageNumber, turboToken) {
    const seedValue = generateSeed()
    const imageUrls = {}
    
    // Initialize with credit info
    imageUrls._system = 'Powered by Click Grow'
    imageUrls._developer = CREDIT_OWNER
    imageUrls._channel = CREDIT_CHANNEL
    imageUrls._generated_at = new Date().toISOString()

    for (let i = 0; i < imageNumber; i++) {
        const data = {
            prompt: prompt,
            seed: seedValue + i,
            width: 576,
            height: 1024,
            steps: 4,
            safety_filter: true,
            enhance: true,
            submission_time: Math.floor(Date.now() / 1000),
            customer_id: "not_signed_in",
            // Embedded credit in prompt
            _credit: `Generated by ${CREDIT_OWNER}`
        }

        const result = await fetchWithAuth(GENERATE_TURBO_URL, data, turboToken)

        if (result.http_code === 200) {
            const responseData = JSON.parse(result.response)
            const base64Image = responseData.image
            if (base64Image) {
                const imageUrl = await uploadToImgBB(base64Image)
                imageUrls[`image_url_${i + 1}`] = imageUrl
                // Add metadata with credit for each image
                imageUrls[`image_${i + 1}_info`] = {
                    prompt: prompt,
                    seed: seedValue + i,
                    generated_by: CREDIT_OWNER,
                    watermark: 'Click Grow'
                }
            } else {
                return {
                    error: "Error uploading image to ImgBB.",
                    credit: CREDIT_OWNER,
                    contact: CREDIT_CHANNEL
                }
            }
        } else {
            return {
                error: `Error: HTTP status code ${result.http_code}`,
                developer: CREDIT_OWNER,
                support: CREDIT_CHANNEL,
                note: 'Please report issues to Click Grow'
            }
        }
    }

    return imageUrls
}

function getRandomUserAgent() {
    const userAgents = [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3 [Powered by Click Grow]",
        "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36 [Developer: Click Grow]",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36 [AI by Click Grow]"
    ]
    return userAgents[Math.floor(Math.random() * userAgents.length)]
}

async function handleRequest(request) {
    const url = new URL(request.url)
    const prompt = url.searchParams.get('prompt')
    const imageNumber = parseInt(url.searchParams.get('image'), 10)

    if (!prompt || isNaN(imageNumber)) {
        return new Response(JSON.stringify({ 
            error: 'Invalid parameters.', 
            developer: CREDIT_OWNER,
            usage: 'Add ?prompt=YOUR_PROMPT&image=NUMBER',
            example: 'https://your-worker.workers.dev/?prompt=cat&image=2',
            contact: CREDIT_CHANNEL
        }, null, 2), { 
            status: 400,
            headers: { 
                'Content-Type': 'application/json', 
                'Access-Control-Allow-Origin': '*',
                'X-Developed-By': CREDIT_OWNER,
                'X-Official-Channel': CREDIT_CHANNEL
            } 
        })
    }

    try {
        const turboToken = await fetchTurboToken()
        if (!turboToken) {
            return new Response(JSON.stringify({ 
                error: 'Error fetching turboToken.',
                developer: CREDIT_OWNER,
                support: CREDIT_CHANNEL
            }, null, 2), { 
                status: 500,
                headers: { 
                    'Content-Type': 'application/json', 
                    'Access-Control-Allow-Origin': '*',
                    'X-Powered-By': CREDIT_OWNER
                } 
            })
        }

        const imageUrls = await fetchAndDisplayImages(prompt, imageNumber, turboToken)
        
        // Ensure credit is always in response
        const responseData = {
            ...imageUrls,
            metadata: {
                developer: CREDIT_OWNER,
                channel: CREDIT_CHANNEL,
                generated_at: new Date().toISOString(),
                version: '1.0',
                copyright: `© ${new Date().getFullYear()} Click Grow. All rights reserved.`
            }
        }

        if (imageUrls.error) {
            responseData.credit = CREDIT_OWNER
            responseData.note = 'For support, contact Click Grow'
            return new Response(JSON.stringify(responseData, null, 2), { 
                status: 500,
                headers: { 
                    'Content-Type': 'application/json', 
                    'Access-Control-Allow-Origin': '*',
                    'X-Developer': CREDIT_OWNER
                } 
            })
        } else {
            return new Response(JSON.stringify(responseData, null, 2), { 
                status: 200, 
                headers: { 
                    'Content-Type': 'application/json', 
                    'Access-Control-Allow-Origin': '*',
                    'X-Powered-By': CREDIT_OWNER,
                    'X-Official-Channel': CREDIT_CHANNEL,
                    'X-Developer-Credit': 'Click Grow',
                    'X-Watermark': 'Generated by Click Grow AI'
                } 
            })
        }
    } catch (error) {
        return new Response(JSON.stringify({ 
            error: 'An unexpected error occurred.',
            developer: CREDIT_OWNER,
            contact: CREDIT_CHANNEL,
            note: 'Please report this error to Click Grow',
            timestamp: new Date().toISOString()
        }, null, 2), { 
            status: 500,
            headers: { 
                'Content-Type': 'application/json', 
                'Access-Control-Allow-Origin': '*',
                'X-Error-Handled-By': CREDIT_OWNER
            } 
        })
    }
}

            
